name: Python CI

# Ativo apenas para execução manual:
on: 
  workflow_dispatch
 
# Desativado para não rodar automaticamente (como a automação funcionva):
# on:
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main
#  schedule:
#    - cron: '0 11 * * *'  
#    - cron: '0 19 * * *'  
#    - cron: '0 1 * * *'   

jobs:
  build:
    runs-on: ubuntu-latest

    env:  
      POSTGRESS_HOST: ${{ secrets.POSTGRESS_HOST }}
      POSTGRESS_PORT: ${{ secrets.POSTGRESS_PORT }}
      POSTGRESS_DATABASE: ${{ secrets.POSTGRESS_DATABASE }}
      POSTGRESS_USER: ${{ secrets.POSTGRESS_USER }}
      POSTGRESS_PASSWORD: ${{ secrets.POSTGRESS_PASSWORD }}
      KEY: ${{ secrets.KEY }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Run script
        run: |
          python main.py

